import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { computeFingerprint, conversationKey } from "./index.js";
import { normalizeTokens } from "./normalize.js";

// The cross-language contract: every vector generated by the normative Go
// implementation must reproduce bit-exactly here. On mismatch, fix the TS
// side — NEVER regenerate the vectors from TS.
interface Vector {
  name: string;
  input: string;
  salt: string;
  too_short: boolean;
  normalized_tokens?: string[];
  simhash?: string;
  exact_hash?: string;
  minhash_b64?: string;
  band_keys?: string[];
  simhash_global?: string;
  conversation_key?: string;
}

// Vendored from the normative Go implementation. Maintainers refresh with
// scripts/sync-fingerprint-vectors.sh; never regenerate from TypeScript.
const vectorsPath = fileURLToPath(
  new URL("./testdata/test_vectors.json", import.meta.url),
);
const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, "utf8"));

describe("golden vectors (canonical, generated by Go)", () => {
  it("has the expected vector count", () => {
    expect(vectors.length).toBeGreaterThanOrEqual(16);
  });

  for (const v of vectors) {
    it(v.name, () => {
      const fp = computeFingerprint(v.input, v.salt, { minHash: true, global: true });
      expect(fp.tooShort).toBe(v.too_short);
      if (v.too_short) return;
      expect(normalizeTokens(v.input, true)).toEqual(v.normalized_tokens);
      expect(fp.simhash).toBe(v.simhash);
      expect(fp.exactHash).toBe(v.exact_hash);
      expect(fp.minhashB64).toBe(v.minhash_b64);
      expect(fp.bandKeys).toEqual(v.band_keys);
      expect(fp.simhashGlobal).toBe(v.simhash_global);
      expect(conversationKey(v.input, v.salt)).toBe(v.conversation_key);
    });
  }
});
